"""Integration tests for ``figures/fig4_identifying_units.py``.

Panel inventory
===============
Figure 4 lays out seven boxes in a 2-column, 4-row grid, lettered A-G top to
bottom, left column then right column:

  A - "Schematic of ElasticNet Reg process": a hand-drawn schematic (plain text
      on a bordered rectangle, no plotted data), composed externally. No script
      generates it. EXCLUDED.
  B - Hazard-rate ElasticNet score curve (binary hz decoder). Line plot, log-x
      "ElasticNet Alpha" (1e0 -> 1e-6) vs. y "Score" (0.0-1.0). Legend: "F1",
      "Accuracy" (single lines -- hz is a binary decode, so no per-label
      split), a horizontal dashed "Chance: 50%" line, and a dash-dot vertical
      "Accuracy: 97%" line marking the last-non-chance alpha. RENDERED -> IN.
  C - Hazard-rate coefficient heatmap. ``pcolor`` over the same log-x alpha
      axis; y-axis is unit index, tick labels "H00".."H14"/"C00".."C14"
      (every other of 32 units: 16 hidden + 16 cell, hidden units plotted
      below cell units) with the vertical axis label "(H)idden / (C)ell Unit
      Number"; colorbar labelled "Coefficient Value"; same dash-dot alpha
      vline as B. RENDERED -> IN.
  D - "Aggregate of identified units / Outer product of hidden and cell unit
      betas to identify pairs": hand-drawn schematic, same as A. EXCLUDED.
  E - Contingency ElasticNet score curve (3-label decoder). Same axes as B.
      Legend: "F1 - Label 0", "F1 - Label 1", "F1 - Label 2", "Accuracy"
      (per-label F1 -- 3-class decode), horizontal dashed "Chance: 33%"
      (= 1/3), dash-dot vertical "Accuracy: 57%". RENDERED -> IN.
  F - Contingency coefficient heatmap. Same layout/axis conventions as C
      (same 32-unit tick labels, "Coefficient Value" colorbar), different
      coefficient-value color range (roughly +-0.15 -- NOT asserted here since
      it is data/fit-dependent). RENDERED -> IN.
  G - "Aggregate of identified units / Outer product of hidden and cell unit
      betas to identify pairs": hand-drawn schematic, identical text to D.
      EXCLUDED.

Panel -> stable semantic SVG name, under ``figures/panels/fig4/``. These names
are the contract: the composed figure links to these paths, so an existing
output is never renamed.
  B -> score_curves_hazard_rate.svg
  C -> coef_heatmap_hazard_rate.svg
  E -> score_curves_contingency.svg
  F -> coef_heatmap_contingency.svg

Provenance
----------
The panels are ported from the exploratory analysis notebooks in the sibling
``hmdcpd-analysis`` repo:

  * Renderer: the source's ``plot_coefs_and_metrics`` is DEAD -- it references
    unbound ``_coefs``/``_hline_chance`` (which should be its own
    ``coefs``/``hline_chance`` params; a 2-line typo, not a logic bug) and
    would raise ``NameError`` at call time. A sibling notebook carries a copy
    of the same function with those two lines fixed; the port uses that form.
  * Panel B/C data: the hazard-rate regression pipeline, chance line
    ``hline_chance=0.5``, binary "accuracy"/"f1" metrics.
  * Panel E/F data: a 3-label contingency decode with ``hline_chance=1/3``.
    The source's regression-cast contingency cell computes per-label f1
    (``average=None``) but, as literally read, passes
    ``metrics_to_plot=['accuracy']`` left over from the earlier hazard cell --
    so the data for the "F1 - Label 0/1/2" lines exists but that cell would not
    plot them. The port passes ``metrics_to_plot=['accuracy', 'f1']``. The
    published panel is authoritative for panel *content*; these assertions are
    written against the rendered text, not against a particular source cell.

Scope notes
-----------
  * Panel titles (e.g. "HZ Metrics with Decreasing ElasticNet Alpha") are
    generated by the ported renderers, but no title text is visible above
    panels B/C/E/F in the published figure (each plot area starts directly at
    the tick labels). These tests therefore assert no title string; they do
    assert axis labels, legend text, and tick labels, which are unambiguous.
    Any title added later should use the shared ``HZ``/``CT`` shorthand from
    ``paper_style.SHORTENED_CONDITIONS`` for consistency across the paper.
  * Intercept panel: the source renderers have a third "Intercept Value"
    subplot, commented out in both, and it does not appear in the published
    figure. Not included in EXPECTED_PANELS.
  * fig4's ElasticNet fits run inline in the figure script -- the pipeline's
    one tolerated piece of inline compute -- so cold runs are slow. This
    fixture uses a generous subprocess timeout and the ``LIC_FIG_CACHE_DIR``
    isolation seam so the memoization contract is testable without depending
    on -- or polluting -- the real ``data/cache/fig_transforms``.
"""

from __future__ import annotations

import os
import re
import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
FIG4_SCRIPT = REPO_ROOT / "figures" / "fig4_identifying_units.py"
PANELS_DIR = REPO_ROOT / "figures" / "panels" / "fig4"

EXPECTED_PANELS = [
    "score_curves_hazard_rate.svg",   # B
    "coef_heatmap_hazard_rate.svg",   # C
    "score_curves_contingency.svg",   # E
    "coef_heatmap_contingency.svg",   # F
]

# Panels whose ElasticNet decode is binary (single F1/Accuracy line, no
# per-label split) vs. the 3-label contingency decode (per-label F1 lines).
SCORE_CURVE_PANELS = {
    "score_curves_hazard_rate.svg": "hazard_rate",
    "score_curves_contingency.svg": "contingency",
}
HEATMAP_PANELS = [
    "coef_heatmap_hazard_rate.svg",
    "coef_heatmap_contingency.svg",
]

pytestmark = [pytest.mark.slow, pytest.mark.integration]


@pytest.fixture(scope="module")
def fig4_run(tmp_path_factory):
    """Run figures/fig4_identifying_units.py headlessly, once per test session.

    Overrides the transforms cache-dir seam (``LIC_FIG_CACHE_DIR``, see
    tests/test_fig_transforms.py and tests/test_fig5_panels.py) to an isolated
    tmp dir so this test proves the memoization contract without depending on
    -- or polluting -- the real ``data/cache/fig_transforms``. Panel SVGs, by
    contrast, are written to the REAL ``figures/panels/fig4/`` -- that is the
    actual deliverable this script exists to produce, not a test fixture.

    Timeout is generous (30 min) relative to fig5's 600s: fig4's ElasticNet
    fits run inline in the script (the pipeline's one tolerated piece of inline
    compute) and a cold run sweeps many alphas per decoder; the memoization test below
    exists precisely so a *second* run would be fast, but this fixture only
    ever runs the script once (module-scoped) so it always pays the cold cost.
    """
    cache_dir = tmp_path_factory.mktemp("fig_transforms_cache")
    env = dict(os.environ)
    env["LIC_FIG_CACHE_DIR"] = str(cache_dir)

    result = subprocess.run(
        [sys.executable, str(FIG4_SCRIPT)],
        cwd=REPO_ROOT,
        env=env,
        capture_output=True,
        text=True,
        timeout=1800,
    )
    return result, cache_dir


class TestHeadlessRun:
    def test_script_exists(self):
        # Fails clearly ("script not found") ahead of the subprocess call,
        # rather than as an opaque non-zero-exit / "No such file" surprise.
        assert FIG4_SCRIPT.exists(), f"figure script not found: {FIG4_SCRIPT}"

    def test_exits_zero(self, fig4_run):
        result, _ = fig4_run
        assert result.returncode == 0, (
            "figures/fig4_identifying_units.py exited "
            f"{result.returncode}\n--- stdout ---\n{result.stdout}\n"
            f"--- stderr ---\n{result.stderr}"
        )
        # A nonzero exit here also catches the source's dead-renderer bug
        # (unbound ``_coefs``/``_hline_chance`` -> NameError) if the port
        # ever loses the 2-line fix: the dead form crashes rather than silently
        # producing wrong/empty output, so this assertion alone is a
        # sufficient regression guard.


class TestPanelOutputs:
    @pytest.mark.parametrize("panel_name", EXPECTED_PANELS)
    def test_writes_expected_panel(self, fig4_run, panel_name):
        result, _ = fig4_run
        if result.returncode != 0:
            pytest.fail(f"headless run failed:\n{result.stderr}")
        panel_path = PANELS_DIR / panel_name
        assert panel_path.exists(), f"expected panel not written: {panel_path}"

    @pytest.mark.parametrize("panel_name", EXPECTED_PANELS)
    def test_panel_has_live_text_elements(self, fig4_run, panel_name):
        panel_path = PANELS_DIR / panel_name
        if not panel_path.exists():
            pytest.skip("panel not written; see test_writes_expected_panel")
        content = panel_path.read_text()
        assert "<text" in content, f"{panel_name} has no live <text> elements"

    @pytest.mark.parametrize("panel_name", EXPECTED_PANELS)
    def test_panel_is_a_single_self_contained_svg(self, fig4_run, panel_name):
        # Cheap proxy for "panel, not a composed multi-panel grid" -- exactly
        # one <svg> root element in the document.
        panel_path = PANELS_DIR / panel_name
        if not panel_path.exists():
            pytest.skip("panel not written; see test_writes_expected_panel")
        content = panel_path.read_text()
        assert content.count("<svg") == 1, (
            f"{panel_name} does not look like a single self-contained panel "
            f"(found {content.count('<svg')} <svg> tags)"
        )

    @pytest.mark.parametrize("panel_name", EXPECTED_PANELS)
    def test_panel_is_non_trivial_size(self, fig4_run, panel_name):
        # Cheap proxy against an accidentally-blank/near-empty export.
        panel_path = PANELS_DIR / panel_name
        if not panel_path.exists():
            pytest.skip("panel not written; see test_writes_expected_panel")
        assert panel_path.stat().st_size > 2000, (
            f"{panel_name} is suspiciously small "
            f"({panel_path.stat().st_size} bytes) for a rendered panel"
        )


class TestScoreCurveContent:
    """Published text for panels B (hazard rate) and E (contingency).

    Both share axis labels; they differ in whether F1 is a single line
    ("F1") or split per label ("F1 - Label 0/1/2"), and in their chance
    line's fixed percentage (50% binary vs. 33% = 1/3 for the 3-label
    decode). Neither the exact "Accuracy: NN%" vline value nor any panel
    title is asserted -- see the module docstring's "Scope notes".
    """

    @pytest.mark.parametrize("panel_name", list(SCORE_CURVE_PANELS))
    def test_has_shared_axis_labels(self, fig4_run, panel_name):
        panel_path = PANELS_DIR / panel_name
        if not panel_path.exists():
            pytest.skip("panel not written; see test_writes_expected_panel")
        content = panel_path.read_text()
        assert "ElasticNet Alpha" in content, f"{panel_name} missing x-axis label"
        assert "Score" in content, f"{panel_name} missing y-axis label"
        assert "Accuracy" in content, f"{panel_name} missing an 'Accuracy' legend entry"

    def test_hazard_rate_curve_is_binary(self, fig4_run):
        panel_path = PANELS_DIR / "score_curves_hazard_rate.svg"
        if not panel_path.exists():
            pytest.skip("panel not written; see test_writes_expected_panel")
        content = panel_path.read_text()
        assert "Chance: 50%" in content, "hz decode chance line should read 'Chance: 50%'"
        assert re.search(r"Accuracy:\s*\d+%", content), (
            "expected an 'Accuracy: NN%' vline legend entry"
        )
        # Binary decode: a bare "F1" legend entry, not a per-label split.
        assert "F1" in content
        assert "F1 - Label" not in content, (
            "hazard-rate decode is binary; should not have per-label F1 lines"
        )

    def test_contingency_curve_is_three_label(self, fig4_run):
        panel_path = PANELS_DIR / "score_curves_contingency.svg"
        if not panel_path.exists():
            pytest.skip("panel not written; see test_writes_expected_panel")
        content = panel_path.read_text()
        assert "Chance: 33%" in content, "3-label decode chance line should read 'Chance: 33%' (1/3)"
        assert re.search(r"Accuracy:\s*\d+%", content), (
            "expected an 'Accuracy: NN%' vline legend entry"
        )
        for label in ("F1 - Label 0", "F1 - Label 1", "F1 - Label 2"):
            assert label in content, f"contingency decode missing per-label legend entry {label!r}"


class TestCoefficientHeatmapContent:
    """Published text for panels C (hazard rate) and F (contingency).

    Both heatmaps share the same axis conventions and unit-index tick
    labelling (16 hidden + 16 cell units, alternating labels shown); the
    coefficient-value color range differs per panel (data/fit-dependent) and
    is deliberately NOT asserted here.
    """

    @pytest.mark.parametrize("panel_name", HEATMAP_PANELS)
    def test_has_shared_axis_and_colorbar_labels(self, fig4_run, panel_name):
        panel_path = PANELS_DIR / panel_name
        if not panel_path.exists():
            pytest.skip("panel not written; see test_writes_expected_panel")
        content = panel_path.read_text()
        assert "ElasticNet Alpha" in content, f"{panel_name} missing x-axis label"
        assert "Coefficient Value" in content, f"{panel_name} missing colorbar label"

    @pytest.mark.parametrize("panel_name", HEATMAP_PANELS)
    def test_has_unit_index_tick_labels(self, fig4_run, panel_name):
        panel_path = PANELS_DIR / panel_name
        if not panel_path.exists():
            pytest.skip("panel not written; see test_writes_expected_panel")
        content = panel_path.read_text()
        # Every other of 32 units is labelled (16 hidden + 16 cell): at least
        # the extremes on each side should appear as literal tick text.
        for tick in ("H00", "H14", "C00", "C14"):
            assert tick in content, f"{panel_name} missing unit tick label {tick!r}"


class TestTransformMemoization:
    def test_cache_dir_populated_after_headless_run(self, fig4_run):
        result, cache_dir = fig4_run
        if result.returncode != 0:
            pytest.fail(f"headless run failed:\n{result.stderr}")
        assert cache_dir.exists(), f"transform cache dir was never created: {cache_dir}"
        cached_files = [p for p in cache_dir.rglob("*") if p.is_file()]
        assert cached_files, (
            f"transform cache dir {cache_dir} has no cached results -- fig4's "
            "inline ElasticNet fits should still be memoized via transforms.py's "
            "shared joblib Memory"
        )
